version: "3.7"
services:
    postgres:
        image: 15.3-alpine3.18
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        env_file:
            - ./server/.env
        volumes:
            - postgres:/var/lib/postgresql/data

    backend:
        hostname: "backend"
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "80"
        depends_on:
            - postgres
        env_file:
            - ./server/.env
        networks:
            - nginx-network-buoknoyar

    client:
        hostname: "client"
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000"
        depends_on:
            - "backend"
        networks:
            - nginx-network-buoknoyar

    nginx:
        image: nginx:mainline
        restart: always
        volumes:
            - ./nginx/default.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "backend"
            - "client"
        networks:
            - nginx-network-buoknoyar

volumes:
    postgres:

networks:
    nginx-network-buoknoyar:
        name: nginx-network-buoknoyar
        external: true
