FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install 
RUN npx prisma generate
RUN npm run seed
COPY . .
FROM node:18-alpine
COPY --from=builder	/app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
EXPOSE 1999
CMD ["npm", "run", "start:dev"]